apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: training
    labels:
        app: training
        tier: backend
spec:
    maxReplicas: 10
    metrics:
        - resource:
              name: cpu
              target:
                  averageUtilization: 50
                  type: Utilization
          type: Resource
    minReplicas: 1
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: training
