---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-html
  labels:
    app: nginx
    env: development
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      env: development
      tier: frontend
  template:
    metadata:
      labels:
        app: nginx
        env: development
        tier: frontend
    spec:
      volumes:
        - name: task-pv-storage
          hostPath:
            path: /home/openapianil/samplePV3/test
            type: DirectoryOrCreate
      containers:
        - name: nginx
          image: rgx69/nginx-1:v3
          ports:
            - containerPort: 80
          volumeMounts:
            - name: task-pv-storage
              mountPath: /mnt/sample

