
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  volumeName: nfs-data-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-html
  labels:
    app: nginx
    env: development
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      env: development
      tier: frontend
  template:
    metadata:
      labels:
        app: nginx
        env: development
        tier: frontend
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: nfs-data-pvc
            readOnly: false
      containers:
        - name: nginx
          image: rgx69/nginx-1:v3
          ports:
            - containerPort: 80
          volumeMounts:
            - name: task-pv-storage
              mountPath: /mnt/sample

