apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  storageClassName: ""
  nfs:
    path: "/data/nfs/"
    server: "10.2.0.109"

